### ISSUE TITLE
Annotations don't work

### ISSUE THREAD

**Issue by clehner** [clehner/node-vim-netbeans#1]
In my Vim client, annotations do not show up. I don't know why.

**Comment by sidorares** [comment]
is it still a valid issue? In my setup annotations work just OK

**Comment by clehner** [comment]
I'll assume then that the problem I had was specific to the client I was using, and its build settings.

**Comment by clehner** [comment]
Yep, I see it working here. Nice job with [node-vim-debugger](/sidorares/node-vim-debugger)!

**Comment by sidorares** [comment]
In fact, I'm doing first presentation on vim-debugger today (and have demo agent with chrome dev tools protocol<->vim)  https://rawgithub.com/sidorares/sidorares.github.com/master/presentations/melbjs/0913/index.html#/

**Comment by clehner** [comment]
I hope it went well. The app looks very useful and works well for me.

**Comment by sidorares** [comment]
cool. Feel free to participate - it's currently in a very "weekend hack" state, I'd like to be able to launch debugger from vim with one command or keypres, have multiple debuggers in one vim support (debugging cluster), embedded sourcemeps etc etc
